name: Android CI

on:
  push:
    branches:
      - master  # Run the workflow on pushes to the master branch
  pull_request:
    branches:
      - master  # Run on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build environment

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Make Gradle wrapper executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Step 4: Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: Run unit tests
      - name: Run Unit Tests
        run: ./gradlew test
