name: Android CI

on:
  push:
    branches:
      - master  # Run the workflow on pushes to the master branch
  pull_request:
    branches:
      - master  # Run on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test --continue

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build --continue

      # Create APK Debug
      - name: Build apk debug project (APK) - app module
        run: ./gradlew assembleDebug --continue

      # Create APK Release
      - name: Build apk release project (APK) - app module
        run: ./gradlew assembleRelease --continue

      # Create Bundle AAB Release
      - name: Build app bundle release (AAB) - app module
        run: ./gradlew bundleRelease --continue

      # Upload Artifact Build
      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }} - My Church App - Debug APK
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }} - My Church App - Release APK
          path: app/build/outputs/apk/release/*.apk

      - name: Upload AAB (App Bundle) Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }} - My Church App - AAB Release
          path: app/build/outputs/bundle/release/*.aab
