name: Android CI

on:
  push:
    branches:
      - master  # Run the workflow on pushes to the master branch
  pull_request:
    branches:
      - master  # Run on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build environment

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4.1.0

      # Step 2: Set up Java JDK 17
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 4: Upload the APK as a build artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/app-debug.apk

